### ISSUE TITLE
Look into rkt

### ISSUE THREAD

**Issue by dstelljes** [dstelljes/container-project#6]
Somehow missed [rkt](https://coreos.com/rkt/) when doing initial research. It doesn't look like it's heavily used yet, but the philosophy is neat and it might be worth mentioning.

**Comment by devshawn** [comment]
I like it's philosophy, but from my playing around with it so far, it isn't super usable. It is "1.0" but doing things like running containers, even using Docker images, seems to be a lot more difficult than just using Docker. It says unprivileged users can do things, but from what I've read, that's more like pulling images rather than actually running containers.

It's also more of a hassle to run a container for awhile (like in the background) in the fact it isn't built in and rather suggested to use systemd or such. I'd like to hear what you think of it once you play around with it.

**Comment by dstelljes** [comment]
I think it's good for people who need fine-grained control and are comfortable getting their hands dirty. From what I've read, the whole systemd/upstart thing is for composability--rather than worry about handling services, they plug into a system that's already there. So I'm not sure how much more we want to dig into it... it seems really solid, but the learning curve is definitely a lot higher.

**Comment by devshawn** [comment]
Closing as we've looked into it a good amount, yay.
